### ISSUE TITLE
EACESS: permission denied

### ISSUE THREAD

**Issue by beanbocchi** [khoakomlem/kb2abot#23]
![image](https://user-images.githubusercontent.com/46867018/104130605-3c84a500-53a4-11eb-833d-f2fa12aad9a9.png)
Sol: Sau khi đọc xong cookie, không ghi fbstate vào file, chỉ cần đọc.

**Comment by beanbocchi** [comment]
WIP

**Comment by beanbocchi** [comment]
Nghi vẫn bị lỗi EACESS permission khi lưu datastore :))

**Comment by Citnut** [comment]
mong ad làm file json chứa data để cho bot đỡ lú

**Comment by beanbocchi** [comment]
Có rồi mà
Ở trong folder datastores ấy

**Comment by beanbocchi** [comment]
EACESS chỉ còn xảy ra trong datastore
