### ISSUE TITLE
Thay api simsimi

### ISSUE THREAD

**Issue by Citnut** [khoakomlem/kb2abot#24]
cái api kia bị DDos sập r thay lại
https://api.sfsu.xyz/?text=${encodeURI(message.body)}&format=json&key=kb2abot_sfsu

**Comment by Citnut** [comment]
hmu lại bị sập api rùi @@

**Comment by Citnut** [comment]
26/01/2021 api được phục hồi, tiếp tục sử dụng và không có vấn đề gì

**Comment by beanbocchi** [comment]
Mới sửa lại simsimi vẫn rep khi xài lệnh :v
#30
