### ISSUE TITLE
Thay cấu trúc plugin lần nữa :(

### ISSUE THREAD

**Issue by beanbocchi** [khoakomlem/kb2abot#27]
Dự định: Sẽ không còn khái niệm về utils nữa, các utils hiện tại sẽ chuyển hết sang helpers

Những thứ sẽ bị code lại:
+bootloader (load interface)
+all plugins
+kb2abot-cli create-plugin

Những thứ sẽ bị loại bỏ:
+ utils concept
+ ko đc sử dụng *utils của các plugin khác nữa (liên plugin)

Mục đích: Sẽ dễ sửa chữa plugin hơn khi tất cả file nó cần nằm gọn trong 1 folder (thay vì 2 folder plugins và utils như bản hiện tại *cũ)

Tại sao ko phải là zip?
-> Chuẩn bị cho kb2abot-api, nếu mà làm zip thì rất khó sửa chữa và maintain code

**Comment by Citnut** [comment]
vậy ad ơi cái utils bị loại bỏ thì import utils kiểu trước sẽ bị đổi thành dạng const x = global.abc phải không á @@

**Comment by beanbocchi** [comment]
ko, nó sẽ chuyển hết sang helper, tại utils với helpers là 2 từ nó khá giống nhau nên cho thành 1 khỏi bị nhầm, nó sẽ thành:
const helperA = kb2abot.helpers.helperA;

**Comment by Citnut** [comment]
ò mà nếu ko làm zip thì có thể làm mỗi một thư mục nhỏ trong thư mục plugins là một plugin riêng bên trong lại chứa main.js và các file phụ nếu plugin đó vjp phải ko ad

**Comment by beanbocchi** [comment]
Um, để .zip khó sửa code lắm

**Comment by beanbocchi** [comment]
Prepair for werewolf
