### ISSUE TITLE
Viết lại các hàm của fca trên promise & tương thích với kb2abot (helpers/fca.js)

### ISSUE THREAD

**Issue by beanbocchi** [khoakomlem/kb2abot#34]
Cơ chế nhắn tin mới sẽ là 1 hàng chờ, hàm mới trong thư viện sắp tới sẽ bỏ vào, base sẽ đẩy ra mỗi 100 milisecond
-> Chuẩn bị cho kb2abot-api

**Comment by BadAimWeeb** [comment]
or just wait for fb.js, totally based on promise <(")

**Comment by Hieu299** [comment]
All

**Comment by beanbocchi** [comment]
@BadAimWeeb when?

**Comment by BadAimWeeb** [comment]
idk

**Comment by beanbocchi** [comment]
V3 added (util/fca.js)
