### ISSUE TITLE
một sự tùy chỉnh mang tính sáng tạo cho plugin

### ISSUE THREAD

**Issue by Citnut** [khoakomlem/kb2abot#9]
thêm chức năng ẩn plugin khỏi help

```
hide_plugin: "on" //hoặc hide_plugin: "off"
//chức năng ẩn plugin
//on là ẩn còn off là hiện
```

**Comment by beanbocchi** [comment]
Done

**Comment by beanbocchi** [comment]
em xem thử mẫu này xem ổn không: https://github.com/kb2abot/kb2abot/issues/8#issuecomment-754000746
Tại thường structure plugin hạn chế update lắm, update mà phát sinh lỗi là phải đi viết lại mệt lắm ;))
